### ISSUE TITLE
我为mall-ver开发了配套的后端项目

### ISSUE THREAD

**Issue by seethefruture** [PowerDos/Mall-Vue#10]
使用springboot快速构建的springcloud微服务项目。使用springcloud eureka作服务治理，使用apollo作分布式配置中心，zuul作入口网关，目前完成了会员，商品，订单，评论，秒杀模块。目前与该项目对接完部分功能接口，希望能允许贡献后端

**Comment by PowerDos** [comment]
非常欢迎

**Comment by seethefruture** [comment]
thx

**Comment by PowerDos** [comment]
可以在你的Mall-server目录下，创建一个README.md文件，然后写一些文档，怎么启动，安装，对接之类的，方便后面有人直接使用时可以直接用

**Comment by seethefruture** [comment]
这个正在做的，但是服务端组件较多，可能需要一点时间。MySQL，elasticsearch，redis，logstash，kibana，rabbitmq，docker 等等这个会慢慢同步上去

**Comment by PowerDos** [comment]
好的，后面也可以做成配置好的部署文件，可以用docker-compose文件或者k8s的yaml文件，在部署这块有需要帮忙可以说下。

**Comment by seethefruture** [comment]
好的 这个会持续贡献一点时间 目前只是把基础配置和项目代码提交了

**Comment by PowerDos** [comment]
great

**Comment by seethefruture** [comment]
我修改的前端代码提交到新分支还是master？后端需要部署提供预览吗

**Comment by PowerDos** [comment]
@seethefruture 
1.可以提交在forMallServerSpringBoot分支，这个我创建下分支，修改前端代码主要想要修改哪些，是对接后台数据相关的吗？
2.后端的话，不需要部署提供预留，这个直接是用Github Page展示的，没有用自己的服务器，不过可以在后端文件增加数据，到时候直接脚本跑到数据库

**Comment by seethefruture** [comment]
我提交之后你看一下改动代码你就懂了 
修改了xuex下的js，页面的一些静态数据也修改成了动态。

后端的话我提供了必要的dockerfile和主要配置

**Comment by PowerDos** [comment]
OK，因为master目前是作为GitHub Page页面展示，没有服务器支撑，所以是必须要做成静态页面。页面改动的，提交到forMallServerSpringBoot，后端改动的，还是提交到master。到时候做完，我再到master的readme.md中说明下分支情况就行。

**Comment by seethefruture** [comment]
这个后端是springcloud的套件有点多，到时候如果有docker pull不下来的就直接pull官方镜像然后改我给的config。具体说明都在README里面了
