### ISSUE TITLE
登录页面Typo，是“欢迎登录”不是“欢迎登陆”

### ISSUE THREAD

**Issue by Antares95** [PowerDos/Mall-Vue#2]
https://powerdos.github.io/Mall-Vue/index.html#/login
![批注 2019-04-18 095354](https://user-images.githubusercontent.com/3815939/56331695-0068e400-61c0-11e9-855e-710fa55d805d.jpg)

**Comment by PowerDos** [comment]
谢谢提醒，你可以PR下代码

**Comment by PowerDos** [comment]
小伙伴已修复 #3
