### ISSUE TITLE
这个项目是开源的吗？  直接使用会不会被起诉？没有看到开源协议！

### ISSUE THREAD

**Issue by lxwlyp** [PowerDos/Mall-Vue#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by PowerDos** [comment]
可直接使用

**Comment by seethefruture** [comment]
有技术问题可以在这里讨论，最近精力比较有限，我会尽量提供帮助
