### ISSUE TITLE
Docker 启动服务后无法进行“登录“操作

### ISSUE THREAD

**Issue by ChrisGray0626** [PowerDos/Mall-Vue#37]
根据文档使用 Docker 拉取镜像后并启动，注册成功之后进行登录操作，但是没有任何反应，看网络也没有任何请求发出。

![image](https://github.com/PowerDos/Mall-Vue/assets/41218402/d65e040e-babb-4f01-a2b1-fd95c1bab471)

**Comment by seethefruture** [comment]
您好，registry.cn-beijing.aliyuncs.com/w929732982/mall-web 这个镜像是一个纯净版的前端项目镜像，使用固定的账号登录

**Comment by ChrisGray0626** [comment]
了解了，多谢
