### ISSUE TITLE
iview 版本

### ISSUE THREAD

**Issue by thedanyang** [PowerDos/Mall-Vue#9]
iview  项目版本 2.13.1
iview 最新版本 4.0

**Comment by PowerDos** [comment]
对的，目前没有做更新，需要的话，可以更新完PR上来

**Comment by thedanyang** [comment]
> 对的，目前没有做更新，需要的话，可以更新完PR上来

更新完之后，效果会受影响吗

**Comment by PowerDos** [comment]
可能会造成一些影响，所以做好测试，样式应该问题不大，主要是组件

**Comment by thedanyang** [comment]
> 可能会造成一些影响，所以做好测试，样式应该问题不大，主要是组件

好的，我试一下
